# Generated by Django 2.1.5 on 2019-03-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0005_auto_20190315_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/avatars/def.jpg', null=True, upload_to='avatars/', verbose_name='Изображение'),
        ),
    ]
