# Generated by Django 2.1.5 on 2019-03-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0006_auto_20190318_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/def.jpg', null=True, upload_to='avatars/', verbose_name='Изображение'),
        ),
    ]
